name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Docker version
      run: docker --version
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$GITHUB_RUN_NUMBER
